services:
  frontend:
    build: ./Frontend/mi-app
    env_file: .env
    ports:
      - "${FRONTEND_PORT}:5173"
    volumes:
      - ./Frontend/mi-app:/app # lo que escribes en tu máquina aparece instantáneamente dentro del contenedor
      - /app/node_modules # Protege los node_modules instalados dentro del contenedor
volumes:
  pgdata:
